source "https://rubygems.org"

gem "sass", "~> 3.2.12"
gem "compass", "~> 0.12.2"
gem "singularitygs", "~> 1.1.2"
gem "singularity-extras", "~> 0.0.3"
gem "breakpoint", "~> 2.0.7"
gem "sassy-math", "~> 1.5"
gem "toolkit", "~> 1.3.8"
gem "color-schemer", "~> 0.2.7"
